# Generated by Django 4.0.1 on 2022-01-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100, verbose_name='نام غذا')),
                ('description', models.CharField(max_length=300, verbose_name='توضیحات')),
                ('discount', models.IntegerField(default=0)),
                ('rate', models.IntegerField(verbose_name='امتیاز')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('photo', models.ImageField(upload_to='media/')),
                ('type_food', models.CharField(choices=[('BreakFast', 'صبحانه'), ('Drink', 'نوشیدنی'), ('Lunch', 'ناهار'), ('Dinner', 'شام')], default='DINNER', max_length=20, verbose_name='نوع غذا')),
                ('created', models.DateField(auto_now_add=True, verbose_name='زمان  انتشار')),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
