pipeline {
    agent any


    stages {
        stage('Clone Repo') {
            steps {
                echo "📥 Cloning the repository... (handled by Jenkins SCM)"
                sh '''
                    git clone https://github.com/aliasqardehqani/restaurant-sample.git
                    git checkout Feat/ci_cd
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "🐳 Building Docker image..."
                sh 'docker build -t restaurant-con:1.0.0 .'
            }
        }


        stage('Run Docker Image') {
            steps {
                echo "🚀 Starting services using docker-compose..."
                sh 'docker run -d -p 8008:8008 restaurant-con:1.0.0'
            }
        }

    }

    post {
        success {
            echo "✅ CI/CD pipeline completed successfully."
        }

        failure {
            echo "❌ CI/CD pipeline failed."
        }
    }
}
