pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                echo "📥 Cloning the repository... (handled by Jenkins SCM)"
                sh '''
                    git clone https://github.com/aliasqardehqani/restaurant-sample.git
                '''
            }
        }

        stage('Run Tests') {
            steps {
                echo "🧪 Running Django model tests..."
                sh '''
                    cd restaurant-sample/config
                    pip install -r requirements.txt
                    python manage.py makemigrations --noinput
                    python manage.py migrate --noinput
                    python manage.py test
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "🐳 Building Docker image..."
                sh '''
                    cd restaurant-sample/config
                    docker build -t restaurant-con:1.0.0 .
                '''
            }
        }

        stage('Run Docker Image') {
            steps {
                echo "🚀 Starting services using docker image..."
                sh '''
                    cd restaurant-sample/config
                    docker run -d -p 8008:8008 restaurant-con:1.0.0
                '''
            }
        }
    }

    post {
        success {
            echo "✅ CI/CD pipeline completed successfully."
        }

        failure {
            echo "❌ CI/CD pipeline failed."
        }
    }
}
